version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
        environment:
          USERNAME: root
          USERPASS: rootpass
          DATABASE: mydb
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.24

      - run:
          name: Construir contenedores
          command: |
            docker-compose -f docker-compose.yml up -d --build

      - run:
          name: Esperar a que Mongo esté listo
          command: |
            docker run --network container:api --rm busybox sh -c "until nc -z localhost 27017; do echo Waiting for Mongo...; sleep 2; done"

      - run:
          name: Ejecutar tests
          command: |
            docker exec api npm test  # cambia esto por tu comando real de test

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - setup_remote_docker

      - add_ssh_keys:
          fingerprints:
            - "xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx"

      - run:
          name: Build imagen y enviar al servidor
          command: |
            docker build -t myapp-image .
            docker save myapp-image | bzip2 | ssh usuario@mi-servidor.com 'bunzip2 | docker load'
            ssh usuario@mi-servidor.com 'docker stop api || true && docker rm api || true && docker run -d --name api -p 3000:3000 myapp-image'

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
